get_request_params = [
	{"foo1": "bar1", "foo2": "bar2"},
	{"param1": "value1", "param2": "value2", "param3": "value3"},
	{"search": "test", "limit": 10, "offset": 0},
	{"filter": "active", "sort": "asc", "page": 2},
	{"user": "john_doe", "age": 30, "country": "USA"},
	{"q": "python testing", "lang": "en", "results": 5},
	{"category": "books", "price_min": 10, "price_max": 50},
	{"status": "pending", "priority": "high", "assigned_to": "team_a"},
	{"type": "json", "format": "pretty", "indent": 4},
	{"key1": "value1", "key2": "value2", "key3": "value3", "key4": "value4"},
	{"foo": "bar"},
	{"search": "example", "page": 1, "limit": 20},
	{"filter": "new", "sort": "desc"},
	{"user": "alice", "age": 25, "country": "UK"},
	{"q": "API testing", "lang": "en", "results": 10},
	{"category": "electronics", "price_min": 100, "price_max": 500},
	{"status": "completed", "priority": "low", "assigned_to": "team_b"},
	{"type": "xml", "format": "compact"},
	{"key1": "valueA", "key2": "valueB", "key3": "valueC"},
]
